import { PillarMeta } from '@/types/pestle';

export const PILLARS_CONFIG: PillarMeta[] = [
  {
    key: 'political',
    label: 'Political',
    letter: 'P',
    description: 'Government policy, political stability, foreign trade, and tax policies.',
    accentColor: 'text-violet-400',
    badgeBg: 'bg-violet-500/10 text-violet-300 border-violet-500/30',
    borderCol: 'border-violet-500/20 hover:border-violet-500/50',
    iconName: 'Landmark',
  },
  {
    key: 'economic',
    label: 'Economic',
    letter: 'E',
    description: 'Interest rates, inflation, exchange rates, economic growth, and labor costs.',
    accentColor: 'text-emerald-400',
    badgeBg: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/30',
    borderCol: 'border-emerald-500/20 hover:border-emerald-500/50',
    iconName: 'TrendingUp',
  },
  {
    key: 'social',
    label: 'Social',
    letter: 'S',
    description: 'Demographics, consumer behavior, cultural shifts, and population dynamics.',
    accentColor: 'text-amber-400',
    badgeBg: 'bg-amber-500/10 text-amber-300 border-amber-500/30',
    borderCol: 'border-amber-500/20 hover:border-amber-500/50',
    iconName: 'Users',
  },
  {
    key: 'technological',
    label: 'Technological',
    letter: 'T',
    description: 'R&D, automation, tech infrastructure, patent activity, and digital disruption.',
    accentColor: 'text-cyan-400',
    badgeBg: 'bg-cyan-500/10 text-cyan-300 border-cyan-500/30',
    borderCol: 'border-cyan-500/20 hover:border-cyan-500/50',
    iconName: 'Cpu',
  },
  {
    key: 'legal',
    label: 'Legal',
    letter: 'L',
    description: 'Antitrust laws, employment laws, IP protections, and health/safety regulations.',
    accentColor: 'text-blue-400',
    badgeBg: 'bg-blue-500/10 text-blue-300 border-blue-500/30',
    borderCol: 'border-blue-500/20 hover:border-blue-500/50',
    iconName: 'Scale',
  },
  {
    key: 'environmental',
    label: 'Environmental',
    letter: 'E',
    description: 'Climate policies, carbon footprint regulations, ESG mandates, and natural resources.',
    accentColor: 'text-teal-400',
    badgeBg: 'bg-teal-500/10 text-teal-300 border-teal-500/30',
    borderCol: 'border-teal-500/20 hover:border-teal-500/50',
    iconName: 'Leaf',
  },
];

export const POPULAR_INDUSTRIES = [
  'Renewable Energy',
  'Fintech',
  'Autonomous Vehicles',
  'Artificial Intelligence & SaaS',
  'Semiconductors',
  'Digital Healthcare & MedTech',
  'Electric Mobility & Batteries',
  'Agricultural Technology',
  'Aerospace & Defense',
  'Supply Chain & Logistics',
];

export const POPULAR_COUNTRIES = [
  { name: 'Sri Lanka', flag: '🇱🇰', region: 'South Asia' },
  { name: 'Germany', flag: '🇩🇪', region: 'Europe' },
  { name: 'India', flag: '🇮🇳', region: 'Asia-Pacific' },
  { name: 'United States', flag: '🇺🇸', region: 'North America' },
  { name: 'United Kingdom', flag: '🇬🇧', region: 'Europe' },
  { name: 'Japan', flag: '🇯🇵', region: 'Asia-Pacific' },
  { name: 'Singapore', flag: '🇸🇬', region: 'Southeast Asia' },
  { name: 'France', flag: '🇫🇷', region: 'Europe' },
  { name: 'Brazil', flag: '🇧🇷', region: 'Latin America' },
  { name: 'Australia', flag: '🇦🇺', region: 'Oceania' },
  { name: 'United Arab Emirates', flag: '🇦🇪', region: 'Middle East' },
  { name: 'Canada', flag: '🇨🇦', region: 'North America' },
  { name: 'South Korea', flag: '🇰🇷', region: 'East Asia' },
];
